name: Run Jest testing suite
on:
  workflow_dispatch:
  pull_request:

env:
  NODE_ENV: "test"

jobs:
  testing:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install toolchain
        run: bun install --frozen-lockfile

      - name: Jest With Coverage
        run: bun install --frozen-lockfile && bun run test

      - name: Add Jest Report to Summary
        if: always()
        run: echo "$(cat test-dashboard.md)" >> $GITHUB_STEP_SUMMARY

